name: Flujo CI-CD

on: 
  push:
    branches: 
      - 'feat*'
      - 'master'


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install
        
      - name: Validar estilo de código (Lint)
        run: npm run lint

      - name: Ejecutar pruebas (CI)
        run: npm test

      - name: Compilar proyecto (CD)
        run: npm run build

      - name: Informar final
        run: echo 'proceso finalizado'

