name: Flujo CI-CD

on: 
  push:
    branches: 
      - 'feat*'

# PERMISOS GLOBALES: Ahora aplican tanto para las pruebas como para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout del código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install
        
      - name: Validar estilo de código (Lint)
        run: npm run lint

      - name: Ejecutar pruebas (CI)
        run: npm test

      - name: Compilar proyecto (CD)
        run: npm run build
      
      # Guardamos los archivos listos para la web (el HTML y el JS) como un artefacto temporal
      - name: Subir archivos para despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Sube todo el proyecto (que contiene el index.html en la raíz)

  # 2. ETAPA DE DESPLIEGUE CONTINUO (CD) - Publicar en internet
  deploy:
    needs: build-and-test # ESENCIAL: Solo se ejecuta si el Job de arriba termina en verde (exitoso)
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Desplegar en GitHub Pages master
      id: deployment
      uses: actions/deploy-pages@v4

