name: Flujo CI-CD

on: 
  push:
    branches: 
      - 'feat*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Correrá 3 veces en paralelo

    steps:
      - name: Checkout del código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install
        
      - name: Validar estilo de código (Lint)
        run: npm run lint

      - name: Ejecutar pruebas (CI)
        run: npm test

      - name: Compilar proyecto (CD)
        run: npm run build


